service: capital-cities

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 8080

provider:
  name: aws
  runtime: nodejs18.x

functions:
  get-questions:
    handler: src/get-questions/handler.handler
    events:
      - httpApi:
          path: /get-questions
          method: get

  check-option:
    handler: src/check-option/handler.handler
    events:
      - httpApi:
          path: /check-option
          method: post
